---
- name: Install postgres
  apt: name={{ item }} state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
    - pgtop

- name: Configure postgres remote access
  lineinfile: dest=/etc/postgresql/9.4/main/postgresql.conf regexp="listen_addresses =.*" line="listen_addresses = '*'"
  sudo_user: postgres
  notify: restart postgresql

- name: Configure postgres remote access
  lineinfile: dest=/etc/postgresql/9.4/main/pg_hba.conf line="host all all 10.0.2.2/32 md5"
  sudo_user: postgres
  notify: restart postgresql

# TODO: This moved to common task
# Fix bad syntax in sudoers
# ref: https://github.com/mitchellh/vagrant/issues/892
# ref: https://github.com/opscode/bento/pull/201
#- name: Fix bad syntax in sudoers
#  lineinfile: dest=/etc/sudoers regexp="%sudo\s*ALL=.*NOPASSWD:ALL" line="%sudo ALL=(ALL) NOPASSWD:ALL"

- name: Create user
  postgresql_user: name=root role_attr_flags=SUPERUSER,INHERIT,NOCREATEDB,NOCREATEROLE,NOREPLICATION password="{{ pgsql.root_password }}"
  sudo_user: postgres

- name: Create a new database
  postgresql_db: name={{ mpgsql.root_password }} owner=root
  sudo_user: postgres
