---
- hosts: all
  sudo: yes
  gather_facts: no
  pre_tasks:
    - name: Load config file
      include_vars: "{{ item }}"
      with_items: config_file
  roles:
    #- { role: test, tags: ["test"], when: "test_install" }
    - sources
    - common
    - git
    - prezto
    - dotfiles
    - node
    - hhvm
    - beanstalkd
    - redis
    - supervisor
    - composer
    - php
    - mailcatcher
    - nginx
    - { role: mysql, when: "mysql_install" }
    - { role: postgresql, when: "pgsql_install" }
    - { role: blackfire, when: "blackfire_install" }
    #
    - tool_base
    - { role: tool_beanstalkd-console, when: "beanstalkd_console_install" }
    - { role: tool_redis-commander, when: "redis_commander_install" }
    #
    - finalize
