---
- hosts: all
  sudo: yes
  gather_facts: no
  pre_tasks:
    - name: Load config file
      include_vars: "{{ item }}"
      with_items: config_file
  roles:
    - { role: test, tags: ["test"], when: "test.install" }
    - sources
    - common
    - git
    - prezto
    - dotfiles
    - node
    - hhvm
    - { role: beanstalkd, when: "beanstalkd.install" }
    - supervisor
    - php
    - composer
    - nginx
    #
    - { role: mysql, when: "mysql.install" }
    - { role: postgresql, when: "pgsql.install" }
    - { role: redis, when: "redis.install" }
    #
    - { role: blackfire, when: "blackfire.install" }
    - { role: mailcatcher, when: "mailcatcher.install" }
    - { role: ngrok, when: "ngrok.install" }
    #
    - { role: tool_base, when: "tools.install" }
    - { role: tool_beanstalkd-console, when: "tools.beanstalkd_console.install" }
    - { role: tool_redis-commander, when: "tools.redis_commander.install" }
    #
    - finalize
