---

- name: Add MySQL repository key
  apt_key: url=http://repo.mysql.com/RPM-GPG-KEY-mysql state=present

# Set mysql root password
- debconf: name="mysql-community-server" question="mysql-community-server/data-dir" vtype="select" value=''
- debconf: name="mysql-community-server" question="mysql-community-server/root-pass" vtype="password" value={{ mysql.root_password|default('') }}
- debconf: name="mysql-community-server" question="mysql-community-server/re-root-pass" vtype="password" value={{ mysql.root_password|default('') }}

#- name: Add mysql repository
#  apt_repository: repo='deb http://repo.mysql.com/apt/debian/ wily mysql-5.7' update_cache=yes
#  register: mysql_deb

- name: Add mysql repository
  apt_repository:
    repo: 'deb http://repo.mysql.com/apt/debian/ wily mysql-5.7'
    state: present
    update_cache: yes
  register: mysql_deb

#- name: Add repository for MySQL 5.7
#  apt_repository: repo='ppa:ondrej/mysql-5.7' update_cache=yes
#  register: mysql_deb

- name: Install mysql
  apt: name={{ item }} state=latest
  with_items:
    - mysql-server
    - python-mysqldb
    - mytop
  when: mysql_deb|success
  register: mysql_installed

- name: Copy .my.cnf file
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  when: mysql_installed|success

# Configure MySQL Password Lifetime
#echo "default_password_lifetime = 0" >> /etc/mysql/my.cnf

- name: Configure MySQL Remote Access
  lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp="bind-address.*=.*" line="bind-address = 10.0.2.15"
  notify: restart mysql
  when: mysql_installed|success

- name: Update root password for all hosts
  mysql_user: >
    name=root
    host={{ item }}
    password={{ mysql.root_password|default('') }}
    priv=*.*:ALL,GRANT
  with_items:
    - 10.0.2.2
    - 127.0.0.1
    - ::1
    - localhost
  when: mysql_installed|success

- name: Update homestead password for all hosts
  mysql_user: >
    name=homestead
    host={{ item }}
    password={{ mysql.root_password|default('') }}
    priv=*.*:ALL,GRANT
  with_items:
    - 10.0.2.2
    - 127.0.0.1
    - ::1
    - localhost
  when: mysql_installed|success

- name: Create a new database
  mysql_db: name={{ mysql.database }} collation=utf8_general_ci
  when: mysql_installed|success
