# Virtual system configuration
vm:
  ip: "192.168.13.13"
  memory: 2048
  cpu: 1

# Vagrant box
box:
  name: "boxcutter/ubuntu1504"
  version: "2.0.13"

# User name for VM
user: "vagrant"

# Name of the VM
machine_name: "vagrantlemp"

# Default timezone
timezone: UTC

# Use vagrant cachier plugin
use_cachier: true

# Ansible provision settings
ansible:
  provision: true
  verbose: false

# Shell provision for box cleaning
cleanup: false

# Install components:
# - To install a component set it to true.
# - To leave a component out of the install set the value to false.

# SQL
sqlite:
  install: true
mysql:
  install: true
  root_password: "secret"
  database: "homestead"
pgsql:
  install: true
  root_password: "secret"
  database: "homestead"

# NoSQL
redis:
  install: true

# Composer
composer:
  # Composer global packages
  # See commented examples below for usage; the 'release' is optional, and defaults to '@stable'.
  global_packages: []
    # - { name: phpunit/phpunit, release: "4.7.x" }
    # - { name: phpunit/phpunit, release: "@stable" }
      - { name: laravel/envoy } # envoy need  "symfony/process": "~2.3"
      - { name: laravel/spark-installer}
      - { name: laravel/lumen-installer }
      - { name: laravel/installer }
      - { name: vinkla/climb }
      - { name: hirak/prestissimo }

# Node/NPM global packages
node_global_packages:
  - bower
  - gulp
  - laravel-elixir
  - npm-check-updates
  - ied # https://github.com/alexanderGugel/ied

# Tools
xdebug:
  install: true
mailcatcher:
  install: true
  # Replace php sendmail path for mailcatcher
  sendmail_replace: true
beanstalkd:
  install: true
blackfire:
  install: true
ngrok:
  install: true
  download_url: "https://dl.ngrok.com/ngrok_2.0.19_linux_amd64.zip"

# Applications
applications:
  install: true
  beanstalkd_console:
    install: true
  redis_commander:
    install: true

# Debug message for development test
test:
  install: false
  message: "Debug message test"
