# Virtual system configuration
box:
  ip: "192.168.13.13"
  memory: 2048
  cpu: 1

# Default vagrant box name
default_name: "vagrantlemp"

# Default timezone
timezone: Europe/Istanbul

# Use vagrant cachier plugin
use_cachier: true

# Ansible provision settings
ansible:
  provision: true
  verbose: false

# Install components:
# - To install a component set it to true.
# - To leave a component out of the install set the value to false.

# SQL
mysql:
  install: true
  root_password: "secret"
pgsql:
  install: true
  root_password: "secret"

# NoSQL
redis:
  install: true

mailcatcher:
  install: true
  sendmail_replace: true # Replace php sendmail path for mailcatcher
beanstalkd:
  install: true
blackfire:
  install: true
ngrok:
  install: false

# Tools
tools:
  install: true
  beanstalkd_console:
    install: true
  redis_commander:
    install: true

# For some development test
test:
  install: false
  message: "Debug message test"
