# Virtual system configuration
box:
  ip: "192.168.13.13"
  memory: 2048
  cpu: 1
user: "vagrant"

# Default vagrant box name
default_name: "vagrantlemp"

# Default timezone
timezone: Europe/Istanbul

# Use vagrant cachier plugin
use_cachier: true

# Ansible provision settings
ansible:
  provision: true
  verbose: false

# Install components:
# - To install a component set it to true.
# - To leave a component out of the install set the value to false.

# SQL
sqlite:
  install: true
mysql:
  install: true
  root_password: "secret"
  database: "homestead"
pgsql:
  install: true
  root_password: "secret"
  database: "homestead"

# NoSQL
redis:
  install: true

composer_global_packages:
  laravel/installer: "~1.2"
  laravel/lumen-installer: "~1.0"
  laravel/envoy: "~1.0"

node_global_packages:
  - bower
  - gulp
  - laravel-elixir

# Tools
xdebug:
  install: true
mailcatcher:
  install: true
  sendmail_replace: true # Replace php sendmail path for mailcatcher
beanstalkd:
  install: true
blackfire:
  install: true
ngrok:
  install: true
  download_url: "https://dl.ngrok.com/ngrok_2.0.19_linux_amd64.zip"

# Applications
applications:
  install: true
  beanstalkd_console:
    install: true
  redis_commander:
    install: true

# Debug message for development test
test:
  install: false
  message: "Debug message test"
