---
- name: Add redis repository
  apt_repository: repo='ppa:rwky/redis' update_cache=yes

- name: Install Redis Server
  apt: name={{ item }} state=latest
  with_items:
    - redis-server

- name: Create init script
  template: src=init.tpl dest=/etc/init.d/redis mode=0755
  notify: restart redis

- name: Set to start boot
  service: name=redis enabled=yes
