---
- name: Register Blackfire GPG key
  apt_key: url=https://packagecloud.io/gpg.key

- name: Add Blackfire package list in source.list
  apt_repository: repo='deb http://packages.blackfire.io/debian any main' update_cache=yes

- name: Install Blackfire agent & Blackfire PHP probe
  apt: name={{ item }} state=latest
  with_items:
    - "{{ blackfire-agent }}"
    - "{{ blackfire-php }}"
  notify:
     - restart php5-fpm
