---
# Based on https://github.com/geerlingguy/ansible-role-composer

- name: Set php_executable variable to a default if not defined
  set_fact:
    php_executable: php
  when: php_executable is not defined

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755

- name: Run Composer installer
  command: >
    {{ php_executable }} composer-installer.php
    chdir=/tmp

- name: Move Composer into globally-accessible location
  shell: >
    mv /tmp/composer.phar {{ composer_path }}
    creates={{ composer_path }}

- name: Ensure composer directory exists
  file:
    path: "{{ composer_home_path }}"
    owner: "{{ composer_home_owner }}"
    group: "{{ composer_home_group }}"
    state: directory

# FIXME: Need to move user part of Vagrant-LEMP-Stack
- name: Add GitHub OAuth token for Composer (if configured)
  template:
    src: "auth.json.j2"
    dest: "{{ composer_home_path }}/auth.json"
    owner: "{{ composer_home_owner }}"
    group: "{{ composer_home_group }}"
  when: composer_github_oauth_token != ''

- include: global-require.yml
  when: composer_global_packages|length > 0
