---
php_modules:
  - php7.0-cli
  - php7.0-dev
  - php7.0-fpm
  - php-pgsql
  - php-sqlite3
  - php-gd
  - php-curl
  - php-imap

  # Need test
  - php-mysqlnd
  - php-json
  - php-curl
  - php-imagick
  - php-gmp
  - php-imap
  - php-mcrypt
  - php-memcached
  - php-redis
  - php-intl
  - php-xmlrpc
