---
- name: Install hhvm gpg key
  apt_key: url=http://dl.hhvm.com/conf/hhvm.gpg.key

- name: Add hhvm deb repository
  apt_repository: repo='deb http://dl.hhvm.com/ubuntu utopic main' update_cache=yes

- name: Install hhvm package
  apt: name=hhvm state=latest

# FIXME: "vagrant" {{ user }}  ile değiştirilmeli
- name: Configure hhvm to run as default user
  replace: dest=/etc/default/hhvm regexp='#RUN_AS_USER="www-data"' replace='RUN_AS_USER="vagrant"'
  notify: restart hhvm
