---
- name: Add redis repository
  apt_repository: repo='ppa:rwky/redis' update_cache=yes

- name: Install redis
  apt: name=redis-server state=latest

- name: Create init script
  template: src=init.tpl dest=/etc/init.d/redis mode=0755

- name: Set to start boot
  service: name=redis enabled=yes
