---
- name: Add PHP 5.6 PPA
  apt_repository: repo="ppa:ondrej/php5-5.6" update_cache=yes

- name: Install PHP 5.6
  apt: name="{{ item }}" state=latest force=yes
  with_items: php_packages

- name: Make mcrypt available
  #command: php5enmod mcrypt
  file: src=/etc/php5/mods-available/mcrypt.ini dest=/etc/php5/cli/conf.d/20-mcrypt.ini state=link force=yes

# Install Mailparse PECL Extension

- name: Install mailparse pecl extension
  command: pecl install mailparse
  register: pecl_result
  changed_when: "'already installed' not in pecl_result.stdout"
  failed_when: "pecl_result.stderr or ('ERROR' in pecl_result.stdout)"

- name: Create mailparse.ini
  copy: content="extension=mailparse.so" dest=/etc/php5/mods-available/mailparse.ini

- name: Make mailparse available
  file: src=/etc/php5/mods-available/mailparse.ini dest=/etc/php5/cli/conf.d/20-mailparse.ini state=link force=yes

#- name: Config timezone
#  ini_file: dest=/etc/php5/mods-available/timezone.ini section=Date option=date.timezone value={{ timezone }}
#  notify: restart php5-fpm

# Enable Remote xdebug
- name: enable remote xdebug
  template: src=xdebug.ini dest=/etc/php5/mods-available/xdebug.ini
- file: src=/etc/php5/mods-available/xdebug.ini dest=/etc/php5/fpm/conf.d/20-xdebug.ini state=link force=yes

- name: Set php5-fpm user
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp="{{ item.regex }}" line="{{ item.line }}"
  with_items:
    - {regex: "^user = .*", line: "user = vagrant"}
    - {regex: "^group = .*", line: "group = vagrant"}
    - {regex: "listen.owner.*", line: "listen.owner = vagrant"}
    - {regex: "listen.group.*", line: "listen.group = vagrant"}
    - {regex: "listen.mode.*", line: "listen.mode = 0666"}

#- name: Set some php fpm settings
#  lineinfile: dest=/etc/php5/fpm/php.ini regexp="{{ item.regex }}" line="{{ item.line }}"
#  with_items:
#    - {regex: "error_reporting = .*", line: "error_reporting = E_ALL"}
#    - {regex: "display_errors = .*", line: "display_errors = On"}
#    - {regex: "cgi.fix_pathinfo=.*", line: "cgi.fix_pathinfo=0"}
#    - {regex: "memory_limit = .*", line: "memory_limit = 512M"}
#    - {regex: "date.timezone =.*", line: "date.timezone = UTC"}
- name: Set some PHP-FPM settings
  template: src=php-fpm.ini dest=/etc/php5/fpm/conf.d/00-php.ini

# Set Some PHP CLI Settings
# - name: Set some php cli settings
#   lineinfile: dest=/etc/php5/cli/php.ini regexp="{{ item.regex }}" line="{{ item.line }}"
#   with_items:
#     - {regex: "error_reporting = .*", line: "error_reporting = E_ALL"}
#     - {regex: "display_errors = .*", line: "display_errors = On"}
#     - {regex: "memory_limit = .*", line: "memory_limit = 512M"}
#     - {regex: "date.timezone =.*", line: "date.timezone = UTC"}
- name: Set some php cli settings
  template: src=php.ini dest=/etc/php5/cli/conf.d/00-php.ini
  notify: restart php5-fpm
