---
- name: Install various packages
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items: sys_packages

- name: Set locales
  locale_gen: name={{ item }} state=present
  with_items: locales

- name: Disable SSH last login print
  lineinfile: dest=/etc/ssh/sshd_config regexp="PrintLastLog yes" line="PrintLastLog no"
  notify: restart sshd

- name: Copy ssh config file
  copy: src=ssh_config dest={{ home_dir }}/.ssh/config owner={{ user }} group={{ user }} mode=640

- name: Add default user to www-data
  user: name={{ user }} groups=www-data append=yes

- name: Set up password-less sudo for admin users
  lineinfile: >
    dest=/etc/sudoers
    regexp='^%sudo'
    line='%sudo   ALL=(ALL) NOPASSWD:ALL'
    state=present backup=yes

- name: Create /etc/ssl/certs directory
  file: path={{ home_dir }}/etc/ssl/certs recurse=yes state=directory
#- name: Download cacert.pem
#  get_url: url=http://curl.haxx.se/ca/cacert.pem dest=/etc/ssl/certs/curl_cacert.pem mode=644
- name: Copy cacert.pem
  copy: src=cacert.pem dest={{ home_dir }}/etc/ssl/certs/curl_cacert.pem mode=640
