---
- name: Add PHP 5.6 PPA
  apt_repository: repo="ppa:ondrej/php5-5.6" update_cache=yes

- name: Install PHP 5.6
  apt: name="{{ item }}" state=latest force=yes
  with_items: php_modules

- name: Start php5-fpm service
  service: name=php5-fpm state=started enabled=true

- name: Make mcrypt available
  file: src=/etc/php5/mods-available/mcrypt.ini dest=/etc/php5/cli/conf.d/20-mcrypt.ini state=link force=yes

# Install Mailparse PECL Extension

- name: Install mailparse pecl extension
  command: pecl install mailparse
  register: pecl_result
  changed_when: "'already installed' not in pecl_result.stdout"
  failed_when: "pecl_result.stderr or ('ERROR' in pecl_result.stdout)"

- name: Create mailparse.ini
  copy: content="extension=mailparse.so" dest=/etc/php5/mods-available/mailparse.ini

- name: Make mailparse available
  file: src=/etc/php5/mods-available/mailparse.ini dest=/etc/php5/cli/conf.d/20-mailparse.ini state=link force=yes

#- name: Config timezone
#  ini_file: dest=/etc/php5/mods-available/timezone.ini section=Date option=date.timezone value={{ timezone }}
#  notify: restart php5-fpm

# TODO: Need check for user variable
- name: Set php5-fpm user
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp="{{ item.regex }}" line="{{ item.line }}"
  with_items:
    - {regex: "^user = .*", line: "user = {{ user }}"}
    - {regex: "^group = .*", line: "group = {{ user }}"}
    - {regex: "^;?listen.owner", line: "listen.owner = {{ user }}"}
    - {regex: "^;?listen.group", line: "listen.group = {{ user }}"}
    - {regex: "^;?listen.mode", line: "listen.mode = 0666"}

- name: Set some PHP-FPM settings
  template: src=php-fpm.ini dest=/etc/php5/fpm/conf.d/00-php.ini

- name: Set some PHP-CLI settings
  template: src=php.ini dest=/etc/php5/cli/conf.d/00-php.ini
  notify: restart php5-fpm
