---
- name: Install MailCatcher
  shell: gem install mailcatcher creates=/usr/bin/mailcatcher

- name: Configure PHP Email
  lineinfile: dest=/etc/php5/fpm/conf.d/00-php.ini line="sendmail_path = /usr/bin/env catchmail"
  notify: restart php5-fpm

- name: Configure PHP Email
  lineinfile: dest=/etc/php5/cli/conf.d/00-php.ini line="sendmail_path = /usr/bin/env catchmail"
  when: mailcatcher.sendmail_replace
  notify: restart php5-fpm

- name: Kill MailCatcher
  command: pkill mailcatcher
  ignore_errors: yes

- name: Add mailcatcher starting command in rc.local
  lineinfile: dest=/etc/rc.local insertbefore='^exit' line="/usr/local/bin/mailcatcher --http-ip=0.0.0.0"

- name: Run MailCatcher
  command: mailcatcher --ip=0.0.0.0
