---
- name: Check if installed
  stat: >
    path=/usr/local/bin/ngrok
  register: ngrok_installed

- name: Download package
  get_url: >
    url={{ ngrok.download_url }}
    dest=/usr/src/ngrok.zip
    force=yes
  when: not ngrok_installed.stat.exists

- name: Extract package
  command: >
    unzip ngrok.zip
    chdir=/usr/src/
    creates=/usr/src/ngrok
  when: not ngrok_installed.stat.exists

- name: Remove package
  file: >
    path=/usr/src/ngrok.zip
    state=absent
  when: not ngrok_installed.stat.exists

- name: Install symlink
  file: >
    src=/usr/src/ngrok
    dest=/usr/local/bin/ngrok
    state=link
  when: not ngrok_installed.stat.exists
