---
- name: Copy .my.cnf file
  template: src=my_credentials.cnf dest=/root/.my.cnf owner=root mode=0600

# Install mysql
- debconf: name="mysql-server" question="mysql-server/root_password" vtype="password" value={{ sql_root_password }}
- debconf: name="mysql-server" question="mysql-server/root_password_again" vtype="password" value={{ sql_root_password }}
- name: Install mysql
  apt: name={{ item }} state=latest
  with_items:
    - mysql-server-5.6
    - python-mysqldb
    - mytop

# Configure MySQL Remote Access
- name: Configure MySQL Remote Access
  lineinfile: dest=/etc/mysql/my.cnf regexp="bind-address.*=.*" line="bind-address = 10.0.2.15"
- mysql_user: name=root host=10.0.2.2 priv=*.*:ALL,GRANT password={{ sql_root_password }}
- mysql_user: name=homestead host=10.0.2.2 priv=*.*:ALL,GRANT password={{ sql_root_password }}
- mysql_user: name=homestead host=% priv=*.*:ALL,GRANT password={{ sql_root_password }}
  notify: restart mysql

- name: Create a new database
  mysql_db: name=homestead collation=utf8_general_ci
  #mysql_db: name=homestead

#- name: Create a database user
#  mysql_user: name=root password=secret priv=*.*:ALL host=localhost
