---

- name: Download node.js pre-installer
  get_url:
    url: https://deb.nodesource.com/setup_5.x
    dest: /tmp/nodejs_setup_5.x.sh
    mode: 0755
  register: fetchnodejs

- name: Run node.js pre-installer
  command: >
    bash nodejs_setup_5.x.sh
    chdir=/tmp
  when: fetchnodejs|success

- name: Install NodeJS
  apt: pkg=nodejs state=latest
  when: fetchnodejs|success

- name: Create npm-packages directory
  file: path='{{ home_dir }}/.npm-packages' state=directory owner={{ user }} group={{ user }}
  when: fetchnodejs|success

- name: Copy .npmrc
  copy: src={{ item }} dest={{ home_dir }}/{{ item }} owner={{ user }} group={{ user }} mode=640
  with_items:
    - .npmrc
  when: fetchnodejs|success

- include: global-require.yml
  when: fetchnodejs|success
