---

- name: Node.js | Fetching node.js source
  shell: curl -sL https://deb.nodesource.com/setup_5.x | bash -s
  register: fetchnodejs

- name: Install NodeJS
  apt: pkg=nodejs state=latest update_cache=true
  when: fetchnodejs|success

- name: Create npm-packages directory
  file: path='{{ home_dir }}/.npm-packages' state=directory owner={{ user }} group={{ user }}
  when: fetchnodejs|success

- name: Copy .npmrc
  copy: src={{ item }} dest={{ home_dir }}/{{ item }} owner={{ user }} group={{ user }} mode=640
  with_items:
    - .npmrc
  when: fetchnodejs|success

- name: Install node.js global packages
  npm: name={{ item }} global=yes state=present
  with_items: node_global_packages
  become_user: "{{ user }}"
  when: fetchnodejs|success
