---
- name: Install postgresql
  apt: name={{ item }} state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
    - pgtop

- name: Configure postgresql remote access
  lineinfile: dest=/etc/postgresql/9.4/main/postgresql.conf regexp="listen_addresses =.*" line="listen_addresses = '*'"
  become_user: postgres
  notify: restart postgresql

- name: Configure postgresql remote access
  lineinfile: dest=/etc/postgresql/9.4/main/pg_hba.conf line="host all all 10.0.2.2/32 md5"
  become_user: postgres
  notify: restart postgresql

- name: Create postgresql user
  postgresql_user: >
    name=root
    role_attr_flags=SUPERUSER,INHERIT,NOCREATEDB,NOCREATEROLE,NOREPLICATION
    password="{{ pgsql.root_password|default('') }}"
  become_user: postgres

- name: Create a new postgresql database
  postgresql_db: name={{ pgsql.database }} owner=root
  become_user: postgres
