---

- name: Add PostgreSQL APT repository key
  apt_key:
    id: ACCC4CF8
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add PostgreSQL official APT repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ wily-pgdg main"

- name: Install PostgreSQL
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - "postgresql-{{ pgsql.version }}"
    - "postgresql-contrib-{{ pgsql.version }}"
    - pgtop

- name: Install dependencies for PostgreSQL
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-psycopg2

- name: Configure PostgreSQL remote access
  lineinfile: dest="/etc/postgresql/{{ pgsql.version }}/main/postgresql.conf" regexp="listen_addresses =.*" line="listen_addresses = '*'"
  become_user: postgres
  notify: restart postgresql

- name: Configure PostgreSQL remote access
  lineinfile: dest="/etc/postgresql/{{ pgsql.version }}/main/pg_hba.conf" line="host all all 10.0.2.2/32 md5"
  become_user: postgres
  notify: restart postgresql

- name: Create PostgreSQL user
  postgresql_user: >
    name=root
    role_attr_flags=SUPERUSER,INHERIT,NOCREATEDB,NOCREATEROLE,NOREPLICATION
    password="{{ pgsql.root_password|default('') }}"
  become_user: postgres

- name: Create a new PostgreSQL database
  postgresql_db: name={{ pgsql.database }} owner=root
  become_user: postgres
