---
- name: "Vagrant LEMP Stack - setter"
  hosts: all
  sudo: yes
  gather_facts: no
  pre_tasks:
    - name: Load config file
      include_vars: "{{ item }}"
      with_items: config_file
  roles:
    - { role: test, tags: ["test"], when: "test.install" }
    - common
    - git
    - prezto
    - dotfiles
    - node
    - supervisor
    - hhvm
    - nginx
    #
    - { role: sqlite, when: "sqlite.install" }
    - { role: mysql, when: "mysql.install" }
    - { role: postgresql, when: "pgsql.install" }
    - { role: redis, when: "redis.install" }
    - php
    - { role: xdebug, when: "xdebug.install" }
    - composer
    - dashboard
    #
    - { role: beanstalkd, when: "beanstalkd.install" }
    - { role: blackfire, when: "blackfire.install" }
    - { role: mailcatcher, when: "mailcatcher.install" }
    - { role: ngrok, when: "ngrok.install" }
    #
    - { role: app_base, when: "applications.install" }
    - { role: app_beanstalkd-console, when: "applications.beanstalkd_console.install" }
    - { role: app_redis-commander, when: "applications.redis_commander.install" }
    #
    - finalize
